// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57VfKxzacQnxb-zk404fufvY1A1kTHGw',
    appId: '1:604572152682:web:15fb095c44ab260ad92b13',
    messagingSenderId: '604572152682',
    projectId: 'flutter-social-login-exa-53414',
    authDomain: 'flutter-social-login-exa-53414.firebaseapp.com',
    storageBucket: 'flutter-social-login-exa-53414.appspot.com',
    measurementId: 'G-FGFL8WR12K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBofEmXJQYAxlg_FuuqJdpalYvttmEhUI',
    appId: '1:604572152682:android:679034a39c18b981d92b13',
    messagingSenderId: '604572152682',
    projectId: 'flutter-social-login-exa-53414',
    storageBucket: 'flutter-social-login-exa-53414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOcmJC6Kc9PeeWNugpmoaae8GaLVmzT-c',
    appId: '1:604572152682:ios:f2bd9a82b160c4d6d92b13',
    messagingSenderId: '604572152682',
    projectId: 'flutter-social-login-exa-53414',
    storageBucket: 'flutter-social-login-exa-53414.appspot.com',
    iosBundleId: 'com.example.flutterSocialLogin',
  );
}
